site_name: ""
nav:
     - Home: index.md
     - protected: protected.md

theme:
  name: readthedocs
  logo: img/image.png

pages:
plugins:
  - search
  - encryptcontent: 
      #global_password: 'password'
      title_prefix: '[LOCK]'
      summary: 'Protected content'
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
